OneLine/OneLine.Wep/Models/CouponDTO.cs
namespace OneLine.Wep.Models
{
    public class CouponDTO
    {
        public string Code { get; set; } = null!;
        public int DiscountAmount { get; set; }
        public DateOnly ExpirationDate { get; set; }
    }
}

OneLine/OneLine.Wep/Models/ErrorViewModel.cs
namespace OneLine.Wep.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OneLine/OneLine.Wep/Models/InsertUpdateCoupon.cs
namespace OneLine.Wep.Models
{
    public class InsertUpdateCoupon
    {
        public string Code { get; set; } = null!;
        public int DiscountAmount { get; set; }
        public DateOnly ExpirationDate { get; set; }
    }
}

OneLine/OneLine.Wep/Models/Request.cs
using static OneLine.Wep.Utility.SD;

namespace OneLine.Wep.Models
{
    public class Request
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public required string Url { get; set; }
        public object? Data { get; set; } = null;
        public string AccessToken { get; set; } = string.Empty;
    }
}

OneLine/OneLine.Wep/Models/ResponseDTO.cs
namespace OneLine.Wep.Models
{
    public class ResponseDTO
    {
        public object? Result { get; set; } = null;
        public bool IsSuccess { get; set; } = true;
        public string Message { get; set; } = string.Empty;
    }
}

OneLine/OneLine.Wep/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OneLine.Wep.Models;
using OneLine.Wep.Service.IService;

namespace OneLine.Wep.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService) => _couponService = couponService;

        public async Task<IActionResult> CouponIndex()
        {
            ResponseDTO? response = await _couponService.AllCouponsAsync();
            List<CouponDTO>? coupons = [];

            if (response != null && response.IsSuccess)
                coupons = JsonConvert
                    .DeserializeObject<List<CouponDTO>>(Convert.ToString(response.Result));
            else 
                TempData["error"] = response?.Message;

            return View(coupons);
        }

        public IActionResult CouponCreate() => View();

        [HttpPost]
        public async Task<IActionResult> CouponCreate(InsertUpdateCoupon model)
        {

            if (ModelState.IsValid)
            {
                ResponseDTO? response = await _couponService.InsertAsync(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = response?.Message;
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    TempData["error"] = response?.Message;
                    return View(nameof(CouponCreate));
                }
                    
            }

            return View(model);
        }

        // To display coupon info before delete.
        public async Task<IActionResult> BeforeDelete(string code)
        {
            ResponseDTO? response = await _couponService.FindCouponByCodeAsync(code);

            if (response != null && response.IsSuccess)
            {
                CouponDTO? coupon = JsonConvert.DeserializeObject<CouponDTO>(Convert.ToString(response.Result));
                return View(coupon);
            }
            else
                TempData["error"] = response?.Message;

            return NotFound();
        }

        public async Task<IActionResult> CouponeDelete(string code)
        {
            ResponseDTO? response = await _couponService.DeleteAsync(code);

            return RedirectToAction(nameof(CouponIndex));
        }

    }
}

OneLine/OneLine.Wep/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OneLine.Wep.Models;
using System.Diagnostics;

namespace OneLine.Wep.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OneLine/OneLine.Wep/Views/Coupon/BeforeDelete.cshtml
@model CouponDTO

<form asp-action="BeforeDelete">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Delete Coupon</h1>
        <input asp-for="Code" hidden/>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Code" class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" class="form-control" />                
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Expriation Date</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ExpirationDate" class="form-control" />
            </div>

            <div class="col-5 offset-2">
                <a asp-controller="Coupon" asp-action="CouponIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input asp-controller="Coupon" asp-action="CouponeDelete" type="submit" value="Delete" class="btn btn-danger form-control" />
                
            </div>
        </div>
    </div>
</form>

OneLine/OneLine.Wep/Views/Coupon/CouponCreate.cshtml
@model CouponDTO

<form asp-action="CouponCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Coupon</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" class="form-control" />
                <span asp-validation-for="DiscountAmount" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Expriation Date</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ExpirationDate" class="form-control" />
                <span asp-validation-for="ExpirationDate" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-controller="Coupon" asp-action="CouponIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />

            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OneLine/OneLine.Wep/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDTO>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Coupons List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-controller="Coupon" asp-action="CouponCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Coupon Code</th>
					<th>Discount Amount</th>
					<th>Expiration Date</th>
				</tr>
			</thead>
			<tbody>
				@foreach(var item in Model) {
					<tr>
						<td>@item.Code</td>
						<td>@(item.DiscountAmount.ToString("c"))</td>
						<td>@item.ExpirationDate</td>
						<td>
							<a asp-controller="Coupon" asp-action="BeforeDelete" asp-route-code="@item.Code" class="btn btn-danger">
								<i class="bi bi-trash"></i>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

OneLine/OneLine.Wep/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OneLine/OneLine.Wep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OneLine.Wep</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OneLine.Wep.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OneLine.Wep</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
                                Content Managment
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><br class="dropdown-divider" /></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - OneLine.Wep - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OneLine/OneLine.Wep/Views/Shared/_Notifications.cshtml
@if(TempData["error"] != null) {
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]')
		</script>
}

@if(TempData["success"] != null) {
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]')
		</script>
}